config/routes.rb
Rails.application.routes.draw do
  get 'orderproducts/index'
  get 'orderproducts/show'
  get 'orderproducts/new'
  get 'orderproducts/edit'
  get 'orderproducts/index'
  get 'orderproducts/show'
  get 'orderproducts/edit'
  get 'productitems/index'
  get 'productitems/show'
  get 'productitems/edit'
  resources :orders do
    resources :orderproducts
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'pages#paid'
  
  get 'cart/index'
  get '/cart', to: 'cart#index'
 
 
  devise_for :users do
    resources:orders
  end
  
  get 'vendor' => "products#vendor"
  
  resources :categories
  resources :products
  get 'pages/contact'
  root 'pages#about'
  
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id', to: 'cart#remove'
  post '/search' => 'products#search'
  
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  
  validates :name, :description, :price, :image, presence: true
  validates :price, numericality: {greater_than: 0 }
  validate :correct_image_type
  
  def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/jpeg image.png))
      errors.add(:image, 'jpeg or png only')
      elsif image.attached? == false
      errors.add(:image, 'Please provide an image.')
    end
  end
  
  def thumbnail
    return self.image.variant(resize: '340x300!')
  end
    def page
    return self.image.variant(resize: '500x400!')
    end
  belongs_to :user
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  def vendor
    @products = Product.where(user: current_user).order("created_at DESC")
  end

  # GET /products
  # GET /products.json
  # ASSOCIATE PRODUCTS TO CATEGORIES DISPLAY
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @products = Product.where(category: @category)
    else
    @products = Product.all.order("created_at DESC")
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
    st = "%#{params[:srch]}"
    @products = Product.where("name like ?", st)
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :image)
    end
    
    #Authenticet user for product ownership
    def check_user
      if current_user != @product.user
        redirect_to root_url, alert: "You must own this product to do that"
      end
    end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.association :category %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    </div>
    
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<br>
   <h3 style="text-align: center">PRODUCTS</h3>
<br>
<hr>

<% Category.all.each do |cat| %>
<% end %>
<% Category.where(display_in_nav: true).each do |cat| %>
<% end %>
   <div class="container">
   <div class="row">
    <% @products.each do |product| %>
       <div class="col-md-3">
        <%= link_to image_tag(product.thumbnail), product, style:'width:100%' %>
        
         <br><strong><%= product.name %> </strong>
          <br><%= number_to_currency(product.price, :unit =>"€") %>
          <br>
          <p><%= link_to image_tag("ellipse.png"), product %>  <%= product.user.name %> </p>
        </p>
        <br>
      </div>
    <% end %>
    </div>
    </div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<p id="notice"><%= notice %></p>
   <div class="container">
    <% @products.each do |product| %>
      <div class="itemhols">
        <%= link_to image_tag product.image, style:'width:100%', :class =>"img-fluid img-thumbnail" %>
        
         <p><%= product.name %>
         </p>
          <p><%= product.price %>
          <br>
          <%= product.category.name %>
          </p>
        <p></p>
        <a href="/cart/<%= product.id %>" class ="button">Add to Cart</a>
        <%= link_to 'Show', product,  :class =>"button", :role=>"button" %>
        <%= link_to 'Edit', edit_product_path(product), :class =>"button", :role=>"button" %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },  :class =>"button", :role=>"button" %>
        </p>
      </div>
    <% end %>
    </div>


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<div class="container-shop">
<h5 style="text-align: left; color: #427674"> You are viewing <%= @product.name %></h5>
<hr>
<div class="row">
<div class="col-md-6" style=><%= link_to image_tag(@product.page), product_path %></div>
<div class="col-md-6">
  <p>
  

</p>
  <p>

  <h1><%= @product.name %></h1>
  <h1><%= number_to_currency(@product.price, :unit =>"€") %></h1>
</p>
<p>

  <%= @product.description %>
</p>
<p>

   
   <p><a href="/cart/<%= @product.id %>" class ="cartbut">Add to Cart</a></p>
</p>
<strong>Sold By:</strong> <%= @product.user.name %> 
<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>
 
</div>
</div>
</div>
</div>
<% if current_user == @product.user %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% end %>

app/views/products/vendor.html.erb
<br>
   <h3 style="text-align: center">MY PRODUCTS</h3>
<br>
<hr>
   <div class="container">
   <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3">
        <%= link_to image_tag(product.thumbnail), product, style:'width:100%' %>
        
         <br class="prodtit"><%= product.name %> 
          <br><%= number_to_currency(product.price, :unit =>"€") %>
          <br>
          <p><%= link_to image_tag("ellipse.png"), product %>  <%= product.user.name %> </p>
        <% if (user_signed_in?) && (current_user == product.user) %>
        <%= link_to 'Edit', edit_product_path(product), :class =>"cartbut", :role=>"button" %>
        <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' },  :class =>"cartbut", :role=>"button" %>
        <% end %>
        </p>
      </div>
    <% end %>
    </div>
    </div>