config/routes.rb
Rails.application.routes.draw do
  get 'orderproducts/index'
  get 'orderproducts/show'
  get 'orderproducts/new'
  get 'orderproducts/edit'
  get 'orderproducts/index'
  get 'orderproducts/show'
  get 'orderproducts/edit'
  get 'productitems/index'
  get 'productitems/show'
  get 'productitems/edit'
  resources :orders do
    resources :orderproducts
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'pages#paid'
  
  get 'cart/index'
  get '/cart', to: 'cart#index'
 
 
  devise_for :users do
    resources:orders
  end
  
  get 'vendor' => "products#vendor"
  
  resources :categories
  resources :products
  get 'pages/contact'
  root 'pages#about'
  
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart/:id', to: 'cart#add'
  
  get '/cart/remove/:id', to: 'cart#remove'
  post '/search' => 'products#search'
  
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
 <div class="alert alert-success">
 <button type="button" class="close" data-dismiss="alert">&times;</button>
 <%= flash[:notice] %>
 </div>
 
 <% elsif flash[:error] %>
  <div class="alert alert-error">
 <button type="button" class="close" data-dismiss="alert">&times;</button>
 <%= flash[:error] %>
 </div>
 
  <% elsif flash[:alert] %>
  <div class="alert">
 <button type="button" class="close" data-dismiss="alert">&times;</button>
 <%= flash[:error] %>
 </div>
 
 <% end %>

app/views/layouts/_collections.html.erb
   <h3 style="text-align: center">Handpicked Collections</h3>
   
   <div class="container">
   <div class="row">
    <% Category.limit(3).where(display_in_nav: false).each do |cat| %>
      <div class="col-md-4">
        <br><%= link_to image_tag(cat.thumbnail), products_path(category: cat.name), style:'width:100%' %></br>
        <div class="titover"><h4><%= cat.name %></h4></div>
        
      </div>
      <% end %>
      </div>
      </div>
      

app/views/layouts/_footer.html.erb
    <footer class="footer"><div class="searchsf"> <%= render 'layouts/search' %> </div></footer>
    

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light topNav">
  <a class="navbar-brand"> <%= link_to image_tag("logo.png"), root_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse nav" id="navbarText">
    <ul class="navbar-navi mr-auto">
      <li class="nav-item active">
    <% if current_user && current_user.admin %>
     <li class="nav-item">
        <a><%= link_to "New Category", new_category_path %></a>
      </li>
      <% end %>
        <% if current_user && current_user.vendor %>
     <li class="nav-item">
        <a><%= link_to "My Store", vendor_path %></a>
      </li>
     <li class="nav-item">
        <a><%= link_to "Upload Product", new_product_path %></a>
      </li>

      <% end %>


    </ul>
    <span class="navbar-text ">
     <li class="nav-item">
        <% if current_user %>
        <a href='#'>Hi <%= current_user.name %></a>
        <a><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
      </li>
       <li class="nav-item">
        <a><%= link_to "Cart", cart_path %></a>
      </li>

      <li class="nav-item">
        <% else %>
        <a><%= link_to "Sign In", new_user_session_path %></a>
      </li>      
      <li class="nav-item">
       <a><%= link_to "Register", new_user_registration_path %></a>
       <% end %>
      </li>
    </span>
  </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light botNav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
     <% Category.where(display_in_nav: true).each do |cat| %>
<%= link_to cat.name, products_path(category: cat.name)
%>
<% end %>


    </div>
  </div>
</nav>

app/views/layouts/_recent-products.html.erb
   <h3 style="text-align: center; margin-top: 60px;  margin-bottom: 50px">Newest Items</h3>

   <div class="container">
   <div class="row">
    <% @products.limit(8).order("created_at DESC").each do |product| %>
      <div class="col-md-3">
        <%= link_to image_tag(product.thumbnail), product, style:'width:100%' %>
        
         <br><strong><%= product.name %> </strong>
          <br><%= number_to_currency(product.price, :unit =>"€") %>
          <br>
          <p><%= link_to image_tag("ellipse.png"), product %>  <%= product.user.name %> </p>
        </p>
        <br>
      </div>
    <% end %>
    </div>
    </div>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:srch, "")  %>
<%= text_field_tag(:srch) %>
<%= submit_tag("Search") %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChestnutLane</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>